import test from "node:test";
import assert from "node:assert/strict";
process.env.NODE_ENV="test";
const {extractJson,classifyError,isRetryable,isPermanentError,runWithFallback,health}=await import("./server.js");
test("direct JSON",()=>assert.deepEqual(extractJson('{"a":1}').parsed,{a:1}));
test("fenced JSON",()=>assert.equal(extractJson('```json\n{"a":1}\n```').parsed.a,1));
test("wrapped JSON",()=>assert.equal(extractJson('x {"a":{"b":2}} y').parsed.a.b,2));
test("429 retryable",()=>assert.equal(isRetryable(Object.assign(new Error("rate"),{status:429})),true));
test("503 retryable",()=>assert.equal(isRetryable(Object.assign(new Error("down"),{status:503})),true));
test("401 permanent",()=>assert.equal(isPermanentError(Object.assign(new Error("unauthorized"),{status:401})),true));
test("400 permanent",()=>assert.equal(isPermanentError(Object.assign(new Error("bad request"),{status:400})),true));
test("timeout classified",()=>assert.equal(classifyError(Object.assign(new Error("timed out"),{name:"TimeoutError"})),"network_timeout"));
test("health V2.2",()=>{const h=health();assert.equal(h.version,"0.4.0");assert.equal(h.routing_backend,"static_policy_v2");});
const ok=(model)=>({model,content:'{"ok":true}',attempts:1,retries:0,latency_ms:1,provider_status:"ok",error_class:null});
const transient=(status=503)=>Object.assign(new Error("transient"),{status,attempts:3,retries:2,latency_ms:3,error_class:"5xx_server_error",provider_status:"transient_error"});
test("balanced success no fallback",async()=>{const x=await runWithFallback({requestedProfile:"balanced",messages:[],chat:async({model})=>ok(model)});assert.equal(x.effectiveProfile,"balanced");assert.equal(x.fallbackUsed,false)});
test("balanced 503 then fast",async()=>{let n=0;const x=await runWithFallback({requestedProfile:"balanced",messages:[],chat:async({model})=>{if(n++===0)throw transient();return ok(model)}});assert.equal(x.effectiveProfile,"fast");assert.equal(x.fallbackUsed,true);assert.deepEqual(x.fallbackChain,["balanced","fast"]);assert.equal(x.totalAttempts,4)});
test("deep timeout then balanced",async()=>{let n=0;const x=await runWithFallback({requestedProfile:"deep",messages:[],chat:async({model})=>{if(n++===0)throw Object.assign(new Error("timeout"),{name:"TimeoutError",attempts:3,retries:2});return ok(model)}});assert.equal(x.effectiveProfile,"balanced");assert.equal(x.fallbackUsed,true)});
test("401 no fallback",async()=>{let n=0;await assert.rejects(()=>runWithFallback({requestedProfile:"balanced",messages:[],chat:async()=>{n++;throw Object.assign(new Error("unauthorized"),{status:401,attempts:1,retries:0})}}));assert.equal(n,1)});
test("evalset fast timeout then balanced",async()=>{let n=0;const x=await runWithFallback({requestedProfile:"fast",messages:[],evalset:true,chat:async({model})=>{if(n++===0)throw Object.assign(new Error("timeout"),{name:"TimeoutError",attempts:3,retries:2});return ok(model)}});assert.equal(x.effectiveProfile,"balanced");assert.deepEqual(x.fallbackChain,["fast","balanced"])});
